/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        midnightBackground: '#503658',
        midnightTitle: '#E5AB8A',
        midnightText: '#CFF469',
        blackBackground: '#000000',
        blackTitle: '#E91229',
        blackText: '#F8D4D7',
        cobaltBackground: '#3C00E4',
        cobaltTitle: '#C0AFD0',
        cobaltText: '#9BEFE2',
        mintBackground: '#ABEDBB',
        mintTitle: '#22306D',
        mintText: '#000000',
        crimsonBackground: '#5C1839',
        crimsonTitle: '#FDD3E8',
        crimsonText: '#FF92AD',
        skyBackground: '#154467',
        skyTitle: '#C2F3FF',
        skyText: '#75C7F0',
        yellowBackground: '#433500',
        yellowTitle: '#F6EEB4',
        yellowText: '#F5E147',
        limeBackground: '#CFF469',
        limeTitle: '#000000',
        limeText: '#503658',
        tomatoBackground: '#5E1C16',
        tomatoTitle: '#FBD3CB',
        tomatoText: '#FF977D',
      },
    },
  },
  plugins: [],
};
