import type { Metadata } from 'next';
import { Inter_Tight } from 'next/font/google';
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import './globals.css';

const inter = Inter_Tight({ subsets: ['latin'], variable: '--inter-tight' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${inter.variable}`}>
        <Theme
          accentColor='grass'
          grayColor='sand'
          radius='large'
          scaling='95%'
          appearance='dark'
        >
          {children}
        </Theme>
      </body>
    </html>
  );
}
